name: Github Actions test ok
on: [push]
env:
  ENV_VARIABLE: ok

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
       - name: Run the IF statement
         if: $ENV_VARIABLE == 'kok'
         run: echo $ENV_VARIABLE
