name: Testing

on:
  workflow_dispatch:
    inputs:
      testType:
        type: choice
        description: 'select the test to run'
        options:
          - SmokeTest
          - FeatureFile
          - FullTest
      featureFile:
        description: 'Enter the path with Name of featureFile'
        required: true
